version: '3.8'
services:
  megastore-db:
    image: postgres:13.0
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: megastore
    networks:
      - megastore-net
networks:
  megastore-net: